#!/usr/bin/env python3
"""
Graph500 Binary CSR Adjacency Matrix Visualizer (NumPy / Matplotlib)

Reads Graph500 binary CSR (.bin) graph files generated by kronecker_cuda
and produces a high-resolution visualization of the graph's adjacency matrix.
"""

import sys
import os
import time
import struct
import argparse
import numpy as np
import matplotlib.pyplot as plt


def parse_args():
    parser = argparse.ArgumentParser(
        description="Graph500 Binary CSR (.bin) Adjacency Matrix Visualizer",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument(
        "-i",
        "--input",
        type=str,
        required=True,
        help="Path to input Graph500 binary CSR file (.bin)",
    )
    parser.add_argument(
        "-o",
        "--output",
        type=str,
        default="adjacency_matrix.png",
        help="Output image path for the adjacency matrix plot",
    )
    parser.add_argument(
        "--grid-size",
        type=int,
        default=1024,
        help="Resolution of the 2D binned density grid for large graphs (N > 256)",
    )
    parser.add_argument(
        "--dpi",
        type=int,
        default=150,
        help="DPI resolution for the output image",
    )
    parser.add_argument(
        "--markersize",
        type=float,
        default=0.8,
        help="Marker size for plt.spy plot (for N > 256)",
    )
    parser.add_argument(
        "--color",
        type=str,
        default="black",
        help="Marker color for plt.spy plot (for N > 256)",
    )
    parser.add_argument(
        "--cmap",
        type=str,
        default=None,
        help="Matplotlib colormap for small graphs N <= 256 (default: 'viridis')",
    )
    parser.add_argument(
        "--stats",
        action="store_true",
        help="Print basic graph statistics extracted from the binary CSR file",
    )
    return parser.parse_args()


def load_binary_csr(filepath):
    """
    Reads a Graph500 binary CSR (.bin) file.
    
    Binary Format Header (40 bytes):
      - magic (8 bytes): "GRAPH500"
      - num_vertices (uint64)
      - num_edges (uint64)
      - weighted (uint64)
      - reserved (uint64)
    Arrays:
      - indptr: uint64[num_vertices + 1]
      - indices: uint64[actual_edges]
      - data: double[actual_edges] (if weighted != 0)
    """
    if not os.path.exists(filepath):
        print(f"Error: Binary graph file '{filepath}' not found.", file=sys.stderr)
        sys.exit(1)

    t0 = time.time()
    file_size = os.path.getsize(filepath)

    with open(filepath, "rb") as f:
        header_bytes = f.read(40)
        if len(header_bytes) < 40:
            print(f"Error: File '{filepath}' is too short to contain a valid header.", file=sys.stderr)
            sys.exit(1)

        magic, num_vertices, num_edges_hdr, weighted, reserved = struct.unpack("<8sQQQQ", header_bytes)
        magic_str = magic.decode("ascii", errors="ignore").rstrip("\x00")

        if magic_str != "GRAPH500":
            print(f"Error: Invalid file format (expected 'GRAPH500' magic header, got '{magic_str}').", file=sys.stderr)
            sys.exit(1)

        # Read indptr array
        indptr = np.fromfile(f, dtype=np.uint64, count=num_vertices + 1)
        if len(indptr) < num_vertices + 1:
            print(f"Error: Incomplete indptr array in file '{filepath}'.", file=sys.stderr)
            sys.exit(1)

        actual_edges = int(indptr[-1])

        # Read indices array
        indices = np.fromfile(f, dtype=np.uint64, count=actual_edges)
        if len(indices) < actual_edges:
            print(f"Error: Incomplete indices array in file '{filepath}'.", file=sys.stderr)
            sys.exit(1)

        # Read weights if weighted
        data = None
        if weighted != 0:
            data = np.fromfile(f, dtype=np.float64, count=actual_edges)
            if len(data) < actual_edges:
                print(f"Error: Incomplete data array in file '{filepath}'.", file=sys.stderr)
                sys.exit(1)

    read_time = time.time() - t0
    return {
        "num_vertices": num_vertices,
        "num_edges": actual_edges,
        "weighted": (weighted != 0),
        "indptr": indptr,
        "indices": indices,
        "data": data,
        "file_size_mb": file_size / (1024.0 * 1024.0),
        "read_time_sec": read_time,
    }


def plot_adjacency_matrix(
    graph_data,
    output_filepath,
    grid_size=1024,
    dpi=150,
    cmap_user=None,
    markersize=0.8,
    color="black",
):
    """
    Plots and saves the adjacency matrix of a binary CSR graph.
    
    - For small graphs (N <= 256): Renders exact weighted 2D matrix with colorbar.
    - For large graphs (N > 256): Renders non-zero entries using plt.spy for clean visual sparsity.
    """
    N = graph_data["num_vertices"]
    M = graph_data["num_edges"]
    indptr = graph_data["indptr"]
    indices = graph_data["indices"]
    data = graph_data["data"]
    is_weighted = graph_data["weighted"]

    print(f"Generating Adjacency Matrix plot for N = {N:,}, M = {M:,} edges...")
    t0 = time.time()

    plt.figure(figsize=(8, 8), dpi=dpi)

    if N <= 256:
        # Small graph: full dense 2D weight representation
        cmap = cmap_user if cmap_user else "viridis"
        adj = np.zeros((N, N), dtype=np.float64)

        # Reconstruct source vertex array u
        degrees = np.diff(indptr).astype(np.int64)
        u = np.repeat(np.arange(N, dtype=np.int64), degrees)
        v = indices.astype(np.int64)

        if is_weighted and data is not None:
            adj[u, v] = data
        else:
            adj[u, v] = 1.0

        plt.imshow(adj, cmap=cmap, interpolation="nearest", origin="upper")
        plt.colorbar(label="Edge Weight" if is_weighted else "Adjacency (1/0)")
        plt.title(f"Adjacency Matrix (N={N:,}, Edges={M:,})", fontsize=12, pad=12)

    else:
        # Large graph: use plt.spy for clean sparsity visualization
        degrees = np.diff(indptr).astype(np.int64)
        u = np.repeat(np.arange(N, dtype=np.int64), degrees)
        v = indices.astype(np.int64)

        if N <= 4096:
            # Direct N x N boolean adjacency matrix
            adj = np.zeros((N, N), dtype=bool)
            adj[u, v] = True
            plt.spy(adj, markersize=markersize, color=color)
        else:
            # Grid-binned boolean matrix for massive graphs (N > 4096)
            grid_dim = min(N, grid_size)
            u_bins = (u * grid_dim // N).astype(np.int32)
            v_bins = (v * grid_dim // N).astype(np.int32)

            density_grid, _, _ = np.histogram2d(
                u_bins, v_bins, bins=grid_dim, range=[[0, grid_dim], [0, grid_dim]]
            )
            plt.spy(density_grid > 0, markersize=markersize, color=color)

        plt.title(f"Symmetric Kronecker Graph Adjacency Matrix (N={N:,}, Edges={M:,})", fontsize=12, pad=12)

    plt.xlabel("Target Vertex (v)", fontsize=10)
    plt.ylabel("Source Vertex (u)", fontsize=10)
    plt.tight_layout()

    plt.savefig(output_filepath)
    plt.close()

    render_time = time.time() - t0
    print(f"Saved Adjacency Matrix plot to '{output_filepath}' (rendered in {render_time:.2f}s).")


def print_graph_stats(graph_data):
    N = graph_data["num_vertices"]
    M = graph_data["num_edges"]
    indptr = graph_data["indptr"]
    indices = graph_data["indices"]
    data = graph_data["data"]

    degrees = np.diff(indptr)
    active_sources = np.count_nonzero(degrees)
    max_out_degree = int(np.max(degrees)) if len(degrees) > 0 else 0
    avg_out_degree = M / N if N > 0 else 0.0

    unique_targets = len(np.unique(indices)) if len(indices) > 0 else 0

    total_matrix_entries = float(N) * float(N)
    density = (M / total_matrix_entries) * 100.0 if total_matrix_entries > 0 else 0.0

    print("==================================================")
    print("           Graph CSR Binary Statistics            ")
    print("==================================================")
    print(f"File Size:            {graph_data['file_size_mb']:.2f} MB")
    print(f"Header Read Time:     {graph_data['read_time_sec']:.4f} seconds")
    print(f"Vertices (N):         {N:,}")
    print(f"Edges (M):            {M:,}")
    print(f"Weighted:             {'Yes' if graph_data['weighted'] else 'No'}")
    print(f"Active Source Nodes:  {active_sources:,} / {N:,} ({(active_sources/N)*100.0:.2f}%)")
    print(f"Unique Target Nodes:  {unique_targets:,} / {N:,} ({(unique_targets/N)*100.0:.2f}%)")
    print(f"Avg Out-Degree:       {avg_out_degree:.2f}")
    print(f"Max Out-Degree:       {max_out_degree:,}")
    print(f"Matrix Density:       {density:.6f}%")

    if graph_data["weighted"] and data is not None and len(data) > 0:
        print(f"Min Edge Weight:      {np.min(data):.6f}")
        print(f"Avg Edge Weight:      {np.mean(data):.6f}")
        print(f"Max Edge Weight:      {np.max(data):.6f}")
    print("==================================================")


def main():
    args = parse_args()

    print(f"Loading Graph500 binary file '{args.input}'...")
    graph_data = load_binary_csr(args.input)

    if args.stats:
        print_graph_stats(graph_data)

    plot_adjacency_matrix(
        graph_data,
        output_filepath=args.output,
        grid_size=args.grid_size,
        dpi=args.dpi,
        cmap_user=args.cmap,
        markersize=args.markersize,
        color=args.color,
    )


if __name__ == "__main__":
    main()

